
PROBLEM
=======
Running pd_front_end.py with FSPS installed through pip returns an import error.

CAUSE
=====
Git has not been loaded as a module on the supercomputer node.

TRACEBACK
=========
File "/home/cmcclellan1010/anaconda2/envs/pdenv/lib/python2.7/site-packages/fsps/__init__.py", line 38, in <module>
    raise ImportError("Your FSPS version does not seem to be under git version "
ImportError: Your FSPS version does not seem to be under git version control. FSPS is available on github at https://github.com/cconroy20/fsps and should be cloned from there

SOLUTION
========
Use "ml git"



PROBLEM
=======
Metallicities for stars in the galaxy simulation are outside of the range that fsps can handle.

CAUSE
=====


TRACEBACK
=========
assigning stars to SED bins
Running SPS for Binned SEDs
calculating the SEDs for  1204  bins
delta_chunk_indices =  75
Entering Pool.map multiprocessing for Stellar SED generation
 SSP_GEN ERROR: metallicity outside of range          14
 SSP_GEN ERROR: metallicity outside of range          15
 SSP_GEN ERROR: metallicity outside of range          17
 SSP_GEN ERROR: metallicity outside of range          18
 SSP_GEN ERROR: metallicity outside of range          19
 SSP_GEN ERROR: metallicity outside of range          20
 SSP_GEN ERROR: metallicity outside of range          21
 SSP_GEN ERROR: metallicity outside of range          13

SOLUTION
========
Floor or ceiling these out-of-bounds metallicities with the maximum allowable
or minimum allowable metallicity in fsps.

IMPLEMENTATION
==============
Will change the code to perform the floor/ceiling operation.



PROBLEM
=======
Can't find hyperion / other module when running pd_front_end.py on a cluster node.

CAUSE
=====
The vanilla anaconda path environment variable is prepended and overrides the python environment in which the module is installed. 

TRACEBACK
=========

SOLUTION
========
Move anaconda python path environment variable to end of .bashrc. Simplify load-in procedure to reduce number of things that can go wrong.

IMPLEMENTATION
==============




PROBLEM
=======
pd_front_end.py crashes when trying to load in dust files.

CAUSE
=====
The custom dust files downloaded in the installation procedure were not downloaded as raw files.

TRACEBACK
=========
Traceback (most recent call last):
  File "pd_front_end.py", line 93, in <module>
    m,xcent,ycent,zcent,dx,dy,dz,pf,boost = m_gen(fname,field_add)
  File "sph_tributary.py", line 120, in sph_m_gen
    d = SphericalDust(cfg.par.dustdir+'%s.hdf5'%size)
  File "/home/cmcclellan1010/anaconda2/envs/pdenv/lib/python2.7/site-packages/hyperion/dust/dust_type.py", line 76, in __init__
    self.read(args[0])
  File "/home/cmcclellan1010/anaconda2/envs/pdenv/lib/python2.7/site-packages/hyperion/dust/dust_type.py", line 315, in read
    dt = h5py.File(filename, 'r')
  File "/home/cmcclellan1010/anaconda2/envs/pdenv/lib/python2.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/cmcclellan1010/anaconda2/envs/pdenv/lib/python2.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
IOError: Unable to open file (file signature not found)

SOLUTION
========
On github, "View Raw" needs to be clicked before the file is downloaded. However, one can't do this if using wget. Another solution must be found for compatibility with wget.

Implementation
==============
I will update the troubleshooting docs to have a tip about making sure the files were raw before downloading.
